import Foundation
import SwiftData

struct PaymentAutoGenerator {

    private static let calculator = BillingCycleCalculator()
    private static let shareCalc = SubscriptionShareCalculator()

    /// 為單一訂閱補齊尚未建立的 PaymentRecord（只處理 active / trial）
    static func run(for subscription: Subscription, in context: ModelContext) {
        guard subscription.status == .active || subscription.status == .trial else { return }

        let calendar = Calendar.current
        let today = calendar.startOfDay(for: Date())

        let from: Date
        let exclusiveFrom: Bool

        if let last = subscription.lastAutoGeneratedDate {
            from = calendar.startOfDay(for: last)
            exclusiveFrom = true   // 上次已處理到 from 這天，從之後開始
        } else {
            from = calendar.startOfDay(for: subscription.firstPaymentDate)
            exclusiveFrom = false  // 首次跑，包含 firstPaymentDate 這天
        }

        guard from <= today else { return }

        let allDates = calculator.paymentDates(
            firstPaymentDate: subscription.firstPaymentDate,
            billingCycle: subscription.billingCycle,
            through: today
        )
        let newDates = allDates.filter { exclusiveFrom ? $0 > from : $0 >= from }
        guard !newDates.isEmpty else {
            subscription.lastAutoGeneratedDate = today
            return
        }

        let myAmt = shareCalc.myAmount(for: subscription)
        for date in newDates {
            let record = PaymentRecord(
                paidDate: date,
                amount: myAmt,
                planAmount: subscription.amount,
                currency: subscription.currency,
                subscription: subscription
            )
            context.insert(record)
        }
        subscription.lastAutoGeneratedDate = today
    }

    /// 為所有訂閱補齊
    static func runAll(for subscriptions: [Subscription], in context: ModelContext) {
        for sub in subscriptions { run(for: sub, in: context) }
    }
}
